spring:
  profiles:
    active: core, db
  messages:
    encoding: UTF-8
  mvc:
    servlet:
      path:

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  debug
    org.linlinjava.litemall.core:  DEBUG


