package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallLogicticsTransportDetail;
import org.linlinjava.litemall.db.domain.LitemallLogicticsTransportDetailExample;

public interface LitemallLogicticsTransportDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    long countByExample(LitemallLogicticsTransportDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallLogicticsTransportDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    int insert(LitemallLogicticsTransportDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    int insertSelective(LitemallLogicticsTransportDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    LitemallLogicticsTransportDetail selectOneByExample(LitemallLogicticsTransportDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    LitemallLogicticsTransportDetail selectOneByExampleSelective(@Param("example") LitemallLogicticsTransportDetailExample example, @Param("selective") LitemallLogicticsTransportDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    List<LitemallLogicticsTransportDetail> selectByExampleSelective(@Param("example") LitemallLogicticsTransportDetailExample example, @Param("selective") LitemallLogicticsTransportDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    List<LitemallLogicticsTransportDetail> selectByExample(LitemallLogicticsTransportDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    LitemallLogicticsTransportDetail selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallLogicticsTransportDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    LitemallLogicticsTransportDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallLogicticsTransportDetail record, @Param("example") LitemallLogicticsTransportDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallLogicticsTransportDetail record, @Param("example") LitemallLogicticsTransportDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallLogicticsTransportDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logictics_transport_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallLogicticsTransportDetail record);
}