package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMerchant;
import org.linlinjava.litemall.db.domain.LitemallMerchantExample;

import java.util.List;

public interface LitemallMerchantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    long countByExample(LitemallMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    int insert(LitemallMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    int insertSelective(LitemallMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    LitemallMerchant selectOneByExample(LitemallMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    LitemallMerchant selectOneByExampleSelective(@Param("example") LitemallMerchantExample example, @Param("selective") LitemallMerchant.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    List<LitemallMerchant> selectByExampleSelective(@Param("example") LitemallMerchantExample example, @Param("selective") LitemallMerchant.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    List<LitemallMerchant> selectByExample(LitemallMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    LitemallMerchant selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallMerchant.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    LitemallMerchant selectByPrimaryKey(Integer id);


    List<LitemallMerchant> selectByOwnWay(Integer userId);

    List<LitemallMerchant> selectByMerchantStatus(@Param("userId")Integer userId,@Param("merchantStatus")Integer merchantStatus);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallMerchant record, @Param("example") LitemallMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallMerchant record, @Param("example") LitemallMerchantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallMerchant record);
}