package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserStore;
import org.linlinjava.litemall.db.domain.LitemallUserStoreExample;

import java.util.List;

public interface LitemallUserStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    int insert(LitemallUserStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    LitemallUserStore selectOneByExample(LitemallUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    LitemallUserStore selectOneByExampleSelective(@Param("example") LitemallUserStoreExample example, @Param("selective") LitemallUserStore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    List<LitemallUserStore> selectByExampleSelective(@Param("example") LitemallUserStoreExample example, @Param("selective") LitemallUserStore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    List<LitemallUserStore> selectByExample(LitemallUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    LitemallUserStore selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserStore.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    LitemallUserStore selectByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserStore record, @Param("example") LitemallUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserStore record, @Param("example") LitemallUserStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserStore record);
}