package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallLogisticsTrucks;
import org.linlinjava.litemall.db.domain.LitemallLogisticsTrucksExample;

public interface LitemallLogisticsTrucksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    long countByExample(LitemallLogisticsTrucksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallLogisticsTrucksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    int insert(LitemallLogisticsTrucks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    int insertSelective(LitemallLogisticsTrucks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    LitemallLogisticsTrucks selectOneByExample(LitemallLogisticsTrucksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    LitemallLogisticsTrucks selectOneByExampleSelective(@Param("example") LitemallLogisticsTrucksExample example, @Param("selective") LitemallLogisticsTrucks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    List<LitemallLogisticsTrucks> selectByExampleSelective(@Param("example") LitemallLogisticsTrucksExample example, @Param("selective") LitemallLogisticsTrucks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    List<LitemallLogisticsTrucks> selectByExample(LitemallLogisticsTrucksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    LitemallLogisticsTrucks selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallLogisticsTrucks.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    LitemallLogisticsTrucks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallLogisticsTrucks record, @Param("example") LitemallLogisticsTrucksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallLogisticsTrucks record, @Param("example") LitemallLogisticsTrucksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallLogisticsTrucks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logistics_trucks
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallLogisticsTrucks record);
}