package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallSmsStatusReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_sms_status_report.id
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_sms_status_report.msgId
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    private String msgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_sms_status_report.mobile
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_sms_status_report.report_time
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    private String reportTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_sms_status_report.code
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_sms_status_report.extend
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    private String extend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_sms_status_report.add_time
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    private LocalDateTime addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_sms_status_report.id
     *
     * @return the value of litemall_sms_status_report.id
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_sms_status_report.id
     *
     * @param id the value for litemall_sms_status_report.id
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_sms_status_report.msgId
     *
     * @return the value of litemall_sms_status_report.msgId
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_sms_status_report.msgId
     *
     * @param msgid the value for litemall_sms_status_report.msgId
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_sms_status_report.mobile
     *
     * @return the value of litemall_sms_status_report.mobile
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_sms_status_report.mobile
     *
     * @param mobile the value for litemall_sms_status_report.mobile
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_sms_status_report.report_time
     *
     * @return the value of litemall_sms_status_report.report_time
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public String getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_sms_status_report.report_time
     *
     * @param reportTime the value for litemall_sms_status_report.report_time
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public void setReportTime(String reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_sms_status_report.code
     *
     * @return the value of litemall_sms_status_report.code
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_sms_status_report.code
     *
     * @param code the value for litemall_sms_status_report.code
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_sms_status_report.extend
     *
     * @return the value of litemall_sms_status_report.extend
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_sms_status_report.extend
     *
     * @param extend the value for litemall_sms_status_report.extend
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public void setExtend(String extend) {
        this.extend = extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_sms_status_report.add_time
     *
     * @return the value of litemall_sms_status_report.add_time
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_sms_status_report.add_time
     *
     * @param addTime the value for litemall_sms_status_report.add_time
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sms_status_report
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", msgid=").append(msgid);
        sb.append(", mobile=").append(mobile);
        sb.append(", reportTime=").append(reportTime);
        sb.append(", code=").append(code);
        sb.append(", extend=").append(extend);
        sb.append(", addTime=").append(addTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sms_status_report
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallSmsStatusReport other = (LitemallSmsStatusReport) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMsgid() == null ? other.getMsgid() == null : this.getMsgid().equals(other.getMsgid()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getReportTime() == null ? other.getReportTime() == null : this.getReportTime().equals(other.getReportTime()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getExtend() == null ? other.getExtend() == null : this.getExtend().equals(other.getExtend()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_sms_status_report
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMsgid() == null) ? 0 : getMsgid().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getReportTime() == null) ? 0 : getReportTime().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getExtend() == null) ? 0 : getExtend().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_sms_status_report
     *
     * @mbg.generated Fri Nov 22 09:48:13 CST 2019
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        msgid("msgId", "msgid", "VARCHAR", false),
        mobile("mobile", "mobile", "VARCHAR", false),
        reportTime("report_time", "reportTime", "VARCHAR", false),
        code("code", "code", "VARCHAR", false),
        extend("extend", "extend", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_sms_status_report
         *
         * @mbg.generated Fri Nov 22 09:48:13 CST 2019
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}