package org.linlinjava.litemall.db.domain;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallMerchant {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.merchant_name
     *
     * @mbg.generated
     */
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.merchant_code
     *
     * @mbg.generated
     */
    private String merchantCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.merchant_address
     *
     * @mbg.generated
     */
    private String merchantAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.merchant_pic
     *
     * @mbg.generated
     */
    private String merchantPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.merchant_phone
     *
     * @mbg.generated
     */
    private String merchantPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.merchant_leader
     *
     * @mbg.generated
     */
    private String merchantLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.edit_time
     *
     * @mbg.generated
     */
    private LocalDateTime editTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_merchant.create_date
     *
     * @mbg.generated
     */
    private LocalDate createDate;

    private Integer consigneeId;

    public Integer getConsigneeId() {
        return consigneeId;
    }

    public void setConsigneeId(Integer consigneeId) {
        this.consigneeId = consigneeId;
    }

    private String consigneeName;

    private String consigneePhone;

    public String getConsigneeName() {
        return consigneeName;
    }

    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName;
    }

    public String getConsigneePhone() {
        return consigneePhone;
    }

    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone;
    }

    private Integer merchantStatus;

    public Integer getMerchantStatus() {
        return merchantStatus;
    }

    public void setMerchantStatus(Integer merchantStatus) {
        this.merchantStatus = merchantStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.id
     *
     * @return the value of litemall_merchant.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.id
     *
     * @param id the value for litemall_merchant.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.merchant_name
     *
     * @return the value of litemall_merchant.merchant_name
     *
     * @mbg.generated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.merchant_name
     *
     * @param merchantName the value for litemall_merchant.merchant_name
     *
     * @mbg.generated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.merchant_code
     *
     * @return the value of litemall_merchant.merchant_code
     *
     * @mbg.generated
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.merchant_code
     *
     * @param merchantCode the value for litemall_merchant.merchant_code
     *
     * @mbg.generated
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.merchant_address
     *
     * @return the value of litemall_merchant.merchant_address
     *
     * @mbg.generated
     */
    public String getMerchantAddress() {
        return merchantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.merchant_address
     *
     * @param merchantAddress the value for litemall_merchant.merchant_address
     *
     * @mbg.generated
     */
    public void setMerchantAddress(String merchantAddress) {
        this.merchantAddress = merchantAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.merchant_pic
     *
     * @return the value of litemall_merchant.merchant_pic
     *
     * @mbg.generated
     */
    public String getMerchantPic() {
        return merchantPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.merchant_pic
     *
     * @param merchantPic the value for litemall_merchant.merchant_pic
     *
     * @mbg.generated
     */
    public void setMerchantPic(String merchantPic) {
        this.merchantPic = merchantPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.merchant_phone
     *
     * @return the value of litemall_merchant.merchant_phone
     *
     * @mbg.generated
     */
    public String getMerchantPhone() {
        return merchantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.merchant_phone
     *
     * @param merchantPhone the value for litemall_merchant.merchant_phone
     *
     * @mbg.generated
     */
    public void setMerchantPhone(String merchantPhone) {
        this.merchantPhone = merchantPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.merchant_leader
     *
     * @return the value of litemall_merchant.merchant_leader
     *
     * @mbg.generated
     */
    public String getMerchantLeader() {
        return merchantLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.merchant_leader
     *
     * @param merchantLeader the value for litemall_merchant.merchant_leader
     *
     * @mbg.generated
     */
    public void setMerchantLeader(String merchantLeader) {
        this.merchantLeader = merchantLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.create_time
     *
     * @return the value of litemall_merchant.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.create_time
     *
     * @param createTime the value for litemall_merchant.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.edit_time
     *
     * @return the value of litemall_merchant.edit_time
     *
     * @mbg.generated
     */
    public LocalDateTime getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.edit_time
     *
     * @param editTime the value for litemall_merchant.edit_time
     *
     * @mbg.generated
     */
    public void setEditTime(LocalDateTime editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_merchant.create_date
     *
     * @return the value of litemall_merchant.create_date
     *
     * @mbg.generated
     */
    public LocalDate getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_merchant.create_date
     *
     * @param createDate the value for litemall_merchant.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDate createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", merchantName=").append(merchantName);
        sb.append(", merchantCode=").append(merchantCode);
        sb.append(", merchantAddress=").append(merchantAddress);
        sb.append(", merchantPic=").append(merchantPic);
        sb.append(", merchantPhone=").append(merchantPhone);
        sb.append(", merchantLeader=").append(merchantLeader);
        sb.append(", createTime=").append(createTime);
        sb.append(", editTime=").append(editTime);
        sb.append(", createDate=").append(createDate);
        sb.append(", consigneeId=").append(consigneeId);
        sb.append(", consigneeName=").append(consigneeName);
        sb.append(", consigneePhone=").append(consigneePhone);
        sb.append(", merchantStatus=").append(merchantStatus);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallMerchant other = (LitemallMerchant) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMerchantName() == null ? other.getMerchantName() == null : this.getMerchantName().equals(other.getMerchantName()))
            && (this.getMerchantCode() == null ? other.getMerchantCode() == null : this.getMerchantCode().equals(other.getMerchantCode()))
            && (this.getMerchantAddress() == null ? other.getMerchantAddress() == null : this.getMerchantAddress().equals(other.getMerchantAddress()))
            && (this.getMerchantPic() == null ? other.getMerchantPic() == null : this.getMerchantPic().equals(other.getMerchantPic()))
            && (this.getMerchantPhone() == null ? other.getMerchantPhone() == null : this.getMerchantPhone().equals(other.getMerchantPhone()))
            && (this.getMerchantLeader() == null ? other.getMerchantLeader() == null : this.getMerchantLeader().equals(other.getMerchantLeader()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getEditTime() == null ? other.getEditTime() == null : this.getEditTime().equals(other.getEditTime()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getConsigneeId() == null ? other.getConsigneeId() == null : this.getConsigneeId().equals(other.getConsigneeId()))
            && (this.getConsigneeName() == null ? other.getConsigneeName() == null : this.getConsigneeName().equals(other.getConsigneeName()))
            && (this.getConsigneePhone() == null ? other.getConsigneePhone() == null : this.getConsigneePhone().equals(other.getConsigneePhone()))
            && (this.getMerchantStatus() == null ? other.getMerchantStatus() == null : this.getMerchantStatus().equals(other.getMerchantStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMerchantName() == null) ? 0 : getMerchantName().hashCode());
        result = prime * result + ((getMerchantCode() == null) ? 0 : getMerchantCode().hashCode());
        result = prime * result + ((getMerchantAddress() == null) ? 0 : getMerchantAddress().hashCode());
        result = prime * result + ((getMerchantPic() == null) ? 0 : getMerchantPic().hashCode());
        result = prime * result + ((getMerchantPhone() == null) ? 0 : getMerchantPhone().hashCode());
        result = prime * result + ((getMerchantLeader() == null) ? 0 : getMerchantLeader().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getEditTime() == null) ? 0 : getEditTime().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getConsigneeId() == null) ? 0 : getConsigneeId().hashCode());
        result = prime * result + ((getConsigneeName() == null) ? 0 : getConsigneeName().hashCode());
        result = prime * result + ((getConsigneePhone() == null) ? 0 : getConsigneePhone().hashCode());
        result = prime * result + ((getMerchantStatus() == null) ? 0 : getMerchantStatus().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_merchant
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        merchantName("merchant_name", "merchantName", "VARCHAR", false),
        merchantCode("merchant_code", "merchantCode", "VARCHAR", false),
        merchantAddress("merchant_address", "merchantAddress", "VARCHAR", false),
        merchantPic("merchant_pic", "merchantPic", "VARCHAR", false),
        merchantPhone("merchant_phone", "merchantPhone", "VARCHAR", false),
        merchantLeader("merchant_leader", "merchantLeader", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        editTime("edit_time", "editTime", "TIMESTAMP", false),
        createDate("create_date", "createDate", "DATE", false),
        consigneeName("consignee_name", "consigneeName", "VARCHAR", false),
        consigneePhone("consignee_phone", "consigneePhone", "VARCHAR", false),
        merchantStatus("merchant_status", "merchantStatus", "INTEGER", false),
        consigneeId("consignee_id", "consigneeId", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_merchant
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}