package org.linlinjava.litemall.db.domain;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallLogicsticsTransport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_logicstics_transport.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_logicstics_transport.transit_id
     *
     * @mbg.generated
     */
    private String transitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_logicstics_transport.license_plate_number
     *
     * @mbg.generated
     */
    private String licensePlateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_logicstics_transport.driver
     *
     * @mbg.generated
     */
    private String driver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_logicstics_transport.freight
     *
     * @mbg.generated
     */
    private Integer freight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_logicstics_transport.transit_status
     *
     * @mbg.generated
     */
    private Short transitStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_logicstics_transport.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_logicstics_transport.create_date
     *
     * @mbg.generated
     */
    private LocalDate createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_logicstics_transport.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_logicstics_transport.id
     *
     * @return the value of litemall_logicstics_transport.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_logicstics_transport.id
     *
     * @param id the value for litemall_logicstics_transport.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_logicstics_transport.transit_id
     *
     * @return the value of litemall_logicstics_transport.transit_id
     *
     * @mbg.generated
     */
    public String getTransitId() {
        return transitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_logicstics_transport.transit_id
     *
     * @param transitId the value for litemall_logicstics_transport.transit_id
     *
     * @mbg.generated
     */
    public void setTransitId(String transitId) {
        this.transitId = transitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_logicstics_transport.license_plate_number
     *
     * @return the value of litemall_logicstics_transport.license_plate_number
     *
     * @mbg.generated
     */
    public String getLicensePlateNumber() {
        return licensePlateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_logicstics_transport.license_plate_number
     *
     * @param licensePlateNumber the value for litemall_logicstics_transport.license_plate_number
     *
     * @mbg.generated
     */
    public void setLicensePlateNumber(String licensePlateNumber) {
        this.licensePlateNumber = licensePlateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_logicstics_transport.driver
     *
     * @return the value of litemall_logicstics_transport.driver
     *
     * @mbg.generated
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_logicstics_transport.driver
     *
     * @param driver the value for litemall_logicstics_transport.driver
     *
     * @mbg.generated
     */
    public void setDriver(String driver) {
        this.driver = driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_logicstics_transport.freight
     *
     * @return the value of litemall_logicstics_transport.freight
     *
     * @mbg.generated
     */
    public Integer getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_logicstics_transport.freight
     *
     * @param freight the value for litemall_logicstics_transport.freight
     *
     * @mbg.generated
     */
    public void setFreight(Integer freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_logicstics_transport.transit_status
     *
     * @return the value of litemall_logicstics_transport.transit_status
     *
     * @mbg.generated
     */
    public Short getTransitStatus() {
        return transitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_logicstics_transport.transit_status
     *
     * @param transitStatus the value for litemall_logicstics_transport.transit_status
     *
     * @mbg.generated
     */
    public void setTransitStatus(Short transitStatus) {
        this.transitStatus = transitStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_logicstics_transport.create_time
     *
     * @return the value of litemall_logicstics_transport.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_logicstics_transport.create_time
     *
     * @param createTime the value for litemall_logicstics_transport.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_logicstics_transport.create_date
     *
     * @return the value of litemall_logicstics_transport.create_date
     *
     * @mbg.generated
     */
    public LocalDate getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_logicstics_transport.create_date
     *
     * @param createDate the value for litemall_logicstics_transport.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDate createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_logicstics_transport.create_user
     *
     * @return the value of litemall_logicstics_transport.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_logicstics_transport.create_user
     *
     * @param createUser the value for litemall_logicstics_transport.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logicstics_transport
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", transitId=").append(transitId);
        sb.append(", licensePlateNumber=").append(licensePlateNumber);
        sb.append(", driver=").append(driver);
        sb.append(", freight=").append(freight);
        sb.append(", transitStatus=").append(transitStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUser=").append(createUser);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logicstics_transport
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallLogicsticsTransport other = (LitemallLogicsticsTransport) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTransitId() == null ? other.getTransitId() == null : this.getTransitId().equals(other.getTransitId()))
            && (this.getLicensePlateNumber() == null ? other.getLicensePlateNumber() == null : this.getLicensePlateNumber().equals(other.getLicensePlateNumber()))
            && (this.getDriver() == null ? other.getDriver() == null : this.getDriver().equals(other.getDriver()))
            && (this.getFreight() == null ? other.getFreight() == null : this.getFreight().equals(other.getFreight()))
            && (this.getTransitStatus() == null ? other.getTransitStatus() == null : this.getTransitStatus().equals(other.getTransitStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_logicstics_transport
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTransitId() == null) ? 0 : getTransitId().hashCode());
        result = prime * result + ((getLicensePlateNumber() == null) ? 0 : getLicensePlateNumber().hashCode());
        result = prime * result + ((getDriver() == null) ? 0 : getDriver().hashCode());
        result = prime * result + ((getFreight() == null) ? 0 : getFreight().hashCode());
        result = prime * result + ((getTransitStatus() == null) ? 0 : getTransitStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_logicstics_transport
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        transitId("transit_id", "transitId", "VARCHAR", false),
        licensePlateNumber("license_plate_number", "licensePlateNumber", "VARCHAR", false),
        driver("driver", "driver", "VARCHAR", false),
        freight("freight", "freight", "INTEGER", false),
        transitStatus("transit_status", "transitStatus", "SMALLINT", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        createDate("create_date", "createDate", "DATE", false),
        createUser("create_user", "createUser", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_logicstics_transport
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}