spring:
  profiles:
    active: db, core, wx
  messages:
    encoding: UTF-8

server:
  port: 8082

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  debug
    org.linlinjava.litemall.wx:  DEBUG
    org.linlinjava.litemall:  debug
    com.newxtc: debug
